language: swift
osx_image: xcode9.2
xcode_project: TFFoundation.xcodeproj
script: xcodebuild test -project TFFoundation.xcodeproj -scheme TFFoundation -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.2'
after_success: bash <(curl -s https://codecov.io/bash) -J '^TFFoundation$'
