language: swift
osx_image: xcode9.0
xcode_project: TFFoundation.xcodeproj
script: xcodebuild test -project TFFoundation.xcodeproj -scheme TFFoundation -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' | xcpretty
