language: swift
osx_image: xcode8.3
xcode_project: TFFoundation.xcodeproj
script: xcodebuild test -project TFFoundation.xcodeproj -scheme TFFoundation -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
